- Hola_mundo.py
Se agrego el hola mundo correspendiente a Alejandro Muñoz
> Updated Name

- ppi_19_plan_de_trabajo.md
Añadí el plan de trabajo del informa 4 y 5 respectivamente.
> AlejandroMuñoz (Realizacion plan de trabajo)

- Holamundo.html
Creacion Hola mundo para despliegue en la internet.
> Creacion Hola mundo para despliegue.

- ppi_19_plan_de_trabajo.md
… de corregir el resto de los demas informes. Solo se corrigio los informes 03 y 04
> Cristian: Primera correccion del calendario de trabajo

- ppi_19_plan_de_trabajo.md
Replanteamos el informe 05 para que sea mas especifico acerca de que funcionalidades implementamos y quien es el responsable
> Replantear informe#05

- ppi_19_plan_de_trabajo.md
Añado los ultimos detalles al plan de trabajo
> Cambio al plan

- Inicio.py
Creacion de la app para el despliegue en streamlit.
> InicializacionApp

- Inicio.py
un cambio pequeño a ver si afecta
> David ramirez

- pages/Crear cuenta.py
Se crea la interfaz de registro de usuario con los parametros basicos
> creacion interfaz de registro

- pages/Crear cuenta.py
Añado los comentarios necesarios, modifico el código para que cumpla con PEP8, corrijo un error al importar la librería openpyxl
> Añado comentarios, corrigo error de openpyxl

- pages/Crear cuenta.py
corrigo error de parse ya que lo tomo el excel como un csv
> Update Crear cuenta.py

- pages/Iniciar Sesion.py
Creación de interfaz de inicio de sesión, integrando el Excel de nuestro repositorio
> Update Iniciar Sesion.py

- Inicio.py
para mirar si se corrije el error de la interfaz de registro
> cambio inicio

- pages/Crear cuenta.py
viendo si de verdad necesito openpyxl
> correcciones

- Inicio.py
- pages/Crear cuenta.py
- pages/Iniciar Sesion.py
corrigiendo a todos los modulos de la app para poder continuar
> correciones

- pages/Iniciar Sesion.py
> inicio de sesion

- pages/Crear cuenta.py
- pages/Iniciar Sesion.py
para ver que esta pasando en el archivo csv
> cambios de visualizacion

- Inicio.py
El import relacionado con la traduccion de la reseña generaba errores, por eso procedemos con su eliminacion.
> Eliminacion del import.

- pages/Crear cuenta.py
añado politica de tratamiento de datos personales usando un expander
> Se añado politica de tratamiento de datos

- pages/Crear cuenta.py
se crea columna adicional para cada usuario que representa sus peliculas favoritas
> se crea columna

- Inicio.py
Se añadio la vista para cada pelicula con un click.
> Adicion vista pelicula.

- pages/Crear_cuenta.py
- pages/Iniciar_Sesion.py
paso parametros de un modulo a otro
> parametros

- pages/Crear_cuenta.py
cambio de contraseña y cambio de nombre
> funcionalidades de registro

- pages/Crear_cuenta.py
> comiit de funcionalidad

- Inicio.py
> manejo de error

- pages/Inicio.py
Ahora se muestran las peliculas favoritas actuales al agregar una nueva pelicula favorita ademas se borra el primer elemento que es una lista vacia
> Nuevas funcionalidades

- pages/Inicio.py
> viendo cambios

- pages/Inicio.py
> arreglando problemas de identacion

- pages/Inicio.py
cambios para quitar el try-catch
> arreglando identacion

- pages/Inicio.py
para poder NO borrar cambios hechos por otros compañeros
> cambiando a versiones anteriores

- pages/Inicio.py
> reactualizando la aplicacion

- Iniciar_Sesion.py
- pages/Inicio.py
cambios para permitir la concurrencia de usuarios a la aplicacion
> #1 de concurrencia de usuarrio

- pages/Inicio.py
para la concurrencia de usuarios en la APP
> commit #2 de concurrencia

- Iniciar_Sesion.py
- pages/Inicio.py
dar concurrencia a la APP para la conexion de varios usuarios a la vez
> commit #3 para concurrencia

- pages/Inicio.py
commit para la concurrencia de multiples usuarios en la APP
> commit #4 para concurrencia

- Iniciar_Sesion.py
- pages/Inicio.py
concurrencia de la APP para el uso de multiples usuarios
> commit #5 para la concurrencia

- Iniciar_Sesion.py
- pages/Inicio.py
para el uso simultaneo de varios usuarios en la APP
> commit #6 de concurrencia

- Iniciar_Sesion.py
para el uso multiple de varios usuarios a la vez en la APP
> commit #7 de concucrrencia

- pages/Inicio.py
para el uso de la APP por parte de multiples usuarios
> commit #8 para concurrencia

- pages/Inicio.py
uso de la app sin iniciar sesion
> cambios para uso de la app

- pages/Inicio.py
hasta el ultimo que hizo cristian
> des-hacer los commits
